trigger:
  - master

pool:
  vmImage: macos-12

stages:
- stage: AndroidBuildStage
  dependsOn: []
  displayName: Android Build Stage
  jobs:

  - job: AndroidBuildJob
    displayName: Android Build Job
    steps:

    - task: DownloadSecureFile@1
      name: keyprop
      displayName: Download key properties file
      inputs:
        secureFile: 'key.properties'

    - task: DownloadSecureFile@1
      name: key
      displayName: Download signing key
      inputs:
        secureFile: 'key.jks'    

    - task: Bash@3
      name: copyconfig
      displayName: Copy config files
      inputs:
        targetType: 'inline'
        script: |
          cp $(keyprop.secureFilePath) $(Build.SourcesDirectory)/android/key.properties
          cp $(key.secureFilePath) $(Build.SourcesDirectory)/android/app/key.jks
          
          echo "key.properties copied to $(Build.SourcesDirectory)/android/key.properties"
          echo "key.jks copied to $(Build.SourcesDirectory)/android/app/key.jks"

    - task: FlutterInstall@0
      displayName: "Install Flutter SDK"
      inputs:
        target: 'auto'
        channel: 'stable'
        version: 'latest'

    - task: JavaToolInstaller@0
      displayName: 'Install Java 11'
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    - task: FlutterBuild@0
      displayName: "Build Application Android"
      inputs:
        target: 'apk'
        projectDirectory: '$(Build.SourcesDirectory)'

    # - task: FlutterTest@0
    #   displayName: "Test Application Android"
    #   inputs:
    #     generateCodeCoverageReport: true
    #     projectDirectory: '$(Build.SourcesDirectory)' 

    - task: CopyFiles@2
      displayName: "Copy artifact to staging directory"
      inputs:
        sourceFolder: '$(Agent.BuildDirectory)'
        contents: '**/flutter-apk/**'
        targetFolder: '$(Build.StagingDirectory)'
        flattenFolders: true

    - task: PublishBuildArtifacts@1
      displayName: "Publish Android aab file"
      inputs:
        PathToPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'apk'
        publishLocation: 'Container'  
      