trigger:
  - master

pool:
  vmImage: macos-12

stages:
- stage: AndroidBuildStage
  dependsOn: []
  displayName: Android Build Stage
  jobs:

  - job: AndroidBuildJob
    displayName: Android Build Job
    steps:

    - task: DownloadSecureFile@1
      name: keyprop
      displayName: Download key properties file
      inputs:
        secureFile: 'key.properties'

    - task: DownloadSecureFile@1
      name: key
      displayName: Download signing key
      inputs:
        secureFile: 'key.jks'    

    - task: Bash@3
      name: copyconfig
      displayName: Copy config files
      input:
        targetType: 'inline'
        script:
          cp $(keyprop.secureFilePath) $(Build.SourcesDirectory)/android/key.properties
          echo "key.properties copied to $(Build.SourcesDirectory)/android/key.properties"
          cp $(key.secureFilePath) $(Build.SourcesDirectory)/android/key.jks
          echo "key.jks copied to $(Build.SourcesDirectory)/android/key.jsk"

    - task: FlutterInstall@0
      displayName: "Install Flutter SDK"
      inputs:
        target: 'auto'
        channel: 'stable'
        version: 'latest'

    - task: FlutterBuild@0
      displayName: "Build Application Android"
      inputs:
        target: 'aab'
        projectDirectory: '$(Build.SourcesDirectory)'

    - task: FlutterTest@0
      displayName: "Test Application Android"
      inputs:
        generateCodeCoverageReport: true
        projectDirectory: '$(Build.SourcesDirectory)' 

    - task: CopyFile@2
      displayName: "Copy artifact to staging directory"
      inputs:
        sourceFolder: '$(Agent.BuildDirectory)'
        contents: '**/bundle/**'
        targetFolder: '$(Build.StagingDirectory)'
        flattenFolders: true

    - task: PublishBuildArtifacts@1
      displayName: "Publish Android aab file"
      inputs:
        PathToPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'AAB'
        publishLocation: 'Container'  
      