name: "UniHealth UI CI/CD"
on:
  #pull_request:
  #  branches:
  #    - main
  #    - master
  push:
    branches:
      - main
      - master
env:
  FLUTTER_CHANNEL: 'stable' # 'stable', 'beta', or 'master', default to: 'stable'
  FLUTTER_VERSION: '3.0.1'
  XCODE_VERSION: '13.4'
  PATH_TO_APK: 'build/app/outputs/flutter-apk/app-release.apk'
  PATH_TO_AAB: 'build/app/outputs/bundle/release/unihealth-release.aab'
  PATH_TO_IPA: 'build/ios/ipa/unihealth-release.ipa'

jobs:
  # code-analysis-and-testing:
  #   name: Code Analysis and Testing
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 30
  #   steps:
  #   - name: Checkout Repository
  #     uses: actions/checkout@v1

  #   - name: Setup Flutter
  #     uses: subosito/flutter-action@v2
  #     with:
  #       channel: ${{ env.FLUTTER_CHANNEL }}
  #       # flutter-version: ${{ env.FLUTTER_VERSION }}

  #   - name: Get Pub Dependencies
  #     run: flutter pub get

  #   - name: Flutter Analyze
  #     run: flutter analyze

  #   - name: Flutter Test
  #     run: flutter test
  android:
    name: Android CI/CD
    #needs: code-analysis-and-testing
    runs-on: ubuntu-latest
    timeout-minutes: 30
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          # flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: ${{ env.PATH_TO_APK }}

  # build:
  #   name: Build & Release
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v1

  #     - uses: actions/setup-java@v1
  #       with:
  #         java-version: '12.x'
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: 3.3.2
  #     - run: flutter pub get
  #     - run: flutter build apk --debug --split-per-abi
  #     - name: Push To Releases
  #       uses: ncipollo/release-action@v1
  #       with:
  #         artifacts: "build/app/outputs/apk/debug/*"
  #         tag: v1.0.${{ github.run_number }}
  #         token: ${{ secrets.TOKEN }}

